services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: tradebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  market_data:
    build: .
    command: python -m tradebot.market_data.service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - SYMBOL_MODE=${SYMBOL_MODE:-custom}
      - SYMBOLS=${SYMBOLS:-AAPL,MSFT,AMZN,GOOG,TSLA}
      - MAX_SYMBOLS=${MAX_SYMBOLS:-500}
      - MAX_WEBSOCKET_SYMBOLS=${MAX_WEBSOCKET_SYMBOLS:-30}
      - ALPACA_KEY=${ALPACA_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
      - SERVICE_NAME=market_data
    volumes:
      - ./symbols_cache.json:/app/symbols_cache.json:ro
    depends_on:
      - redis

  alpaca_service:
    build: .
    command: python -m tradebot.market_data.alpaca_service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - ALPACA_KEY=${ALPACA_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
      - SYMBOL_MODE=${SYMBOL_MODE:-custom}
      - SYMBOLS=${SYMBOLS:-AAPL,MSFT,AMZN,GOOG,TSLA}
      - MAX_SYMBOLS=${MAX_SYMBOLS:-500}
      - MAX_WEBSOCKET_SYMBOLS=${MAX_WEBSOCKET_SYMBOLS:-30}
      - SERVICE_NAME=alpaca_service
    depends_on:
      - redis

  polygon_service:
    build: .
    command: python -m tradebot.market_data.polygon_service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - SYMBOL_MODE=${SYMBOL_MODE:-custom}
      - SYMBOLS=${SYMBOLS:-AAPL,MSFT,AMZN,GOOG,TSLA}
      - MAX_SYMBOLS=${MAX_SYMBOLS:-500}
      - MAX_WEBSOCKET_SYMBOLS=${MAX_WEBSOCKET_SYMBOLS:-30}
    depends_on:
      - redis

  strategy:
    build: .
    command: python -m tradebot.strategy.service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=strategy
    depends_on:
      - redis

  execution:
    build: .
    command: python -m tradebot.execution.service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=execution
    depends_on:
      - redis

  storage:
    build: .
    command: python -m tradebot.storage.timeseries_service
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - SERVICE_NAME=storage
    depends_on:
      - redis
      - timescaledb

  api:
    build: .
    command: uvicorn tradebot.api.history_service:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=api
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb

  dashboard:
    build: .
    command: python -m tradebot.dashboard.main
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - SERVICE_NAME=dashboard
    ports:
      - "8001:8001"
    volumes:
      - ./tradebot/dashboard:/app/tradebot/dashboard
    depends_on:
      - redis
      - timescaledb

volumes:
  timescale_data: 