# Load variables from developer overrides (.env)
# .env file lives in the repo root and is git-ignored.

services:
  # ───────── Infrastructure ─────────
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: tradebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tradebot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ───────── Core micro-services ─────
  market_data:
    build: .
    command: python -m tradebot.market_data.service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=market_data
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=synthetic
    volumes:
      - ./symbols_cache.json:/app/symbols_cache.json:ro
    depends_on:
      redis:
        condition: service_healthy
    profiles: [ "synthetic", "default" ]  # Synthetic tick generation

  # Real market data from Alpaca (requires API credentials)
  alpaca_market_data:
    build: .
    command: python -m tradebot.market_data.alpaca_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=alpaca_market_data
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=alpaca
    volumes:
      - ./symbols_cache.json:/app/symbols_cache.json:ro
    depends_on:
      redis:
        condition: service_healthy
    profiles: [ "alpaca" ]  # Only run when explicitly requested

  # Polygon market data service
  polygon_market_data:
    build: .
    command: python -m tradebot.market_data.polygon_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=polygon_market_data
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=polygon
    volumes:
      - ./symbols_cache.json:/app/symbols_cache.json:ro
    depends_on:
      redis:
        condition: service_healthy
    profiles: [ "polygon" ]  # Only run when explicitly requested

  # Yahoo Finance market data service
  yahoo_market_data:
    build: .
    command: python -m tradebot.market_data.yahoo_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=yahoo_market_data
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=yahoo
      - YAHOO_FETCH_INTERVAL=10.0
    volumes:
      - ./symbols_cache.json:/app/symbols_cache.json:ro
    depends_on:
      redis:
        condition: service_healthy
    profiles: [ "yahoo" ]  # Only run when explicitly requested

  strategy:
    build: .
    command: python -m tradebot.strategy.service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=strategy
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=${DATA_SOURCE:-synthetic}
    depends_on:
      redis:
        condition: service_healthy

  execution:
    build: .
    command: python -m tradebot.execution.service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=execution
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=${DATA_SOURCE:-synthetic}
    depends_on:
      redis:
        condition: service_healthy

  storage:
    build: .
    command: python -m tradebot.storage.timeseries_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=storage
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=${DATA_SOURCE:-synthetic}
    depends_on:
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy

  # ───────── API + Dashboard ─────────
  api:
    build: .
    command: python -m tradebot.api.history_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=api
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=${DATA_SOURCE:-synthetic}
    ports: ["8000:8000"]
    depends_on:
      timescaledb:
        condition: service_healthy

  dashboard:
    build: .
    # Mount dashboard directory so HTML/JS edits hot-reload
    volumes:
      - ./tradebot/dashboard:/app/tradebot/dashboard
      - ./models:/app/models
    command: python -m tradebot.dashboard.main
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=dashboard
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - DATA_SOURCE=${DATA_SOURCE:-synthetic}
    ports: ["8001:8001"]
    depends_on:
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy

  # ML Training Service (optional - for scheduled model training)
  ml_training:
    build: .
    command: python -m tradebot.strategy.ml_training_service
    env_file: [ .env ]
    environment:
      - SERVICE_NAME=ml_training
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/tradebot
      - SOURCE_DATA=${SOURCE_DATA:-synthetic}
      - TRAINING_CRON_SCHEDULE=${TRAINING_CRON_SCHEDULE:-0 2,14,22 * * *}
      - TRAINING_BATCH_SIZE=${TRAINING_BATCH_SIZE:-1000}
      - MAX_CONCURRENT_TRAINING_JOBS=${MAX_CONCURRENT_TRAINING_JOBS:-3}
      - TRAINING_JOB_TIMEOUT=${TRAINING_JOB_TIMEOUT:-3600}
      - TRAINING_RETRY_ATTEMPTS=${TRAINING_RETRY_ATTEMPTS:-3}
      - MIN_TRAINING_DATA_POINTS=${MIN_TRAINING_DATA_POINTS:-100}
      - MODEL_RETENTION_DAYS=${MODEL_RETENTION_DAYS:-30}
    volumes:
      - ./models:/app/models
      - ./ml_training_service.log:/app/ml_training_service.log
    depends_on:
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    profiles: [ "ml-training" ]  # Optional service

volumes:
  timescale_data: 